version: '3'
services:
  billing-system-api:
    image: billing-system-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8071:8071"
    command: uvicorn main:app --host 0.0.0.0 --port 8071
