version: '3'
services:
  billing-system-api:
    image: python:3.12
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8071:8071"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8071
